"""Add materials link and tracking flags to Client model

Revision ID: 29b99436cde8
Revises: edd5e68595a9
Create Date: 2026-05-30 16:33:46.922394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b99436cde8'
down_revision = 'edd5e68595a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_reminder_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_followup_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('is_followup_sent')
        batch_op.drop_column('is_reminder_sent')
        batch_op.drop_column('materials_link')

    # ### end Alembic commands ###
